language: generic
os:
- osx
before_script: 
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export CERTIFICATE_P12=Certificate.p12;
    echo $CERTIFICATE_OSX_P12 | base64 --decode > $CERTIFICATE_P12;
    export KEYCHAIN=build.keychain;
    security create-keychain -p mysecretpassword $KEYCHAIN;
    security default-keychain -s $KEYCHAIN;
    security unlock-keychain -p mysecretpassword $KEYCHAIN;
    security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign;
  fi
script:
- bash ./make_osx.sh
deploy:
  provider: releases
  skip_cleanup: true
  edge: true
  api_key: $GITHUB_TOKEN
  overwrite: true
  file_glob: true
  file:
  - "dist/pktwallet-*"
  on:
    branch: master
    tags: true
