language: generic
os:
- osx
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
install:
  - composer install --dev --prefer-dist
script:
- bash ./make_osx.sh
deploy:
  provider: releases
  skip_cleanup: true
  edge: true
  file:
  - dist/PKTWallet.dmg
  on:
    branch: master
    tags: true
env:
  global:
    secure: DdjmnyjXJ1BtpOcJrAqCAEcOA9tYhx7boC1u08F0ruRUzkorEFZ/EEN9WBRVt0YwO7DG4PO/R1fBZ9+F/Mk76uRJhZslb0dmDKFpD3xapXfmeV62vCZnEuoP4LKVVGfgxle++ttFjkrcfjuvP4E+fotzC4Gaj0o50yHuYNXi9YzvvPHf67Xt7Qn9JeyKkqPCnqxVdz7IQcrWIxija72rfpsVH4AxpeQcIBpRwQQ6Bmx8ZPIaniI2+qJvYRSSueLpvn/b/BzLlWPC6QOp4/2AybxCFwraVheAwMKUfTXmXyzBmZ4wKRGFxfR32EWUybAh94NmDdTWyyFpuZHbxVizBdmSYolTqs5tHV9GSvbx7fgh9KPRuvKYG29rwsp4mcxAkbCQBPcmhh87s2/0QAgidt9Rq02Bwnq3b9qawMJL8Sq5Y6PWp8693JCaRz80LKj/I/YXj7RCBT4E1kJ8r2vaBe0Q3h+TUtz0hvsoZf4bdbsIoVk8MiYqyVRtiyCqNEMK2SL73lh8IhuvGsXcgIwc2OrtpMpdpIPcO5DE1wbsTOR+rfUEshTcn3OYcRU5YNHv2fprEfpAGDsuZpsjbV6ditws+3eUX9tDdZIJtyKUem6ZKVOqX7JDQrXB2nAxNGm1Md3YP/DMfXTbXibzEgVbkgbbX1MJsVVkpYcntQNsEJA=
