language: generic

os:
  - osx

before_install:

script:
  - bash ./make_osx.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 7kRccuQ7JeM2zf9j2vF0sgLaZtGgvzB1Oz75NRWfvjih49IzMhHgojRX7pQOKQ6oZEaOFxQ1tLrrjOZmlfpZxEIijZ4yuPutRIm6Nf+zyKSx07n5LHUPzydiU482K9M7usII5l8jPXK6e4MoNexVPD2vxBeydBoIh9lyW9vhpk1oktbsvteWSAP0yMg5JXkMhMBVctfdHabPTzmYku97pDa1G9zuuKIGwECm09V0Exvjjq2rqfsjvveIHzg9fn2ZIabWtz6W3GkyTyWLBkTThBM6gCRnRY4Qc2CgtV9T4qD+xgz1jloH1NZpJyKa8nIj76tFf1aWeLJf0QfA4lU11gpUjSzG7pyDoKSQZkkJT5d4sfUJWJ6RgKYC0pOGDjKMIR/CM539dHeCTtqjnj9bZIjnVMTzfRZQE0geYvzOMsmiJYJA5ceBvY1jMKdnTRQe1XVkCUXzTggmKaQ/o6hpj8jynbr07ojfBkLCLONlye9miw4LfhvAfY0l/SkCPa1uVWuHtGHFiw5CFwoub8T0+7vgUirsUGCgtTwMwy+QrA60TlEU/G0j61QyIoeqoDjg++Bz55vwxXVryUjhlTHoey8YbHKagOHO65XGUcZuR6VEVSSwooK//2OnFwGiA36Ua4go5Ktm2/SpvDwry37o2doK7dicGpILDeeDSocUsmU=
  edge: true
  file:
    - "dist/PKTWallet.dmg"
  on:
    branch: master
    tags: true
    
    
