language: generic
jobs:
  include:
    - os: osx
      osx_image: xcode8.3
before_install: 
script:
- bash ./make_osx.sh
deploy:
  provider: releases
  skip_cleanup: true
  edge: true
  api_key: $GITHUB_TOKEN
  overwrite: true
  file_glob: true
  file:
  - "dist/pktwallet-*"
  on:
    branch: master
    tags: true