language: generic

os:
  - osx

before_install:

script:
  - bash ./make_osx.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  keep_history: true
  file:
    - "dist/PKTWallet.dmg"
  on:
    branch: master
    tags: true
    
    
