language: generic

os:
  - osx

before_install:

script:
  - bash ./make_osx.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 5tjqnZ/CaoNV7EWIPgGRPjo5IF22fwiWHqml1VH2I9j0AqKKU8SgJY9RGRg+dz0aDjSA9HC5pwiWWaD1ATkuUFVlYhyR9sdBW7tA3UZIf9RJ0VhPndVjsBrdG7Guz353taEDZrZCsjFPX+4QthvkrrIn80JDLCKXE7lnjSRr1+NqTp4YQdprsFJ8V7aVGbxHcn+Npr6BrQSoxAIFCmqD81VWFEfPZVviUMPSeUBiqgQltgsZiVJA8jOiJVm77HJnMv7oEUtns60yIiQHrhctfVt8Naz9xAJ3L29EGMdTQLOD7ITWsxOyfJnlWWeDpTE5I5of16vC9CAlPDiJptKRbkjQC2RSIO/fMJt+4iulffYfvB9vLRxDb9twKUJQLU4lyA/3d8qPE/vZ6dP46N45wDVF87REv6ILrmrNGR83y3usDmmRAo/3PNl80vBaVCH70FcPidocGiHkPl1p+ng8OHKBnj/HqUIdKViao+zMAiErjDGoBZiR+XLmTJtIhYNjYxTq7RQwAoe+yyc0USEIdtJ2IdcTAaA+D3A+Ot1RiIA+cJBlg09LCADxpReRjzfM0dFUGW3KWTAHNmyK0IpED2p0CrvoSIcOuemaFti8yBUCRDSSgwMamKE8S692ndYMcY6CHwIAwB/m1jtYxjpyTNu/k6+6eK3ofUhfnTAqQMg=
  edge: true
  file:
    - "dist/PKTWallet.dmg"
  on:
    branch: master
    tags: true
    
    
